name: codebreaker
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  camera: ^0.10.0+1
  google_mlkit_text_recognition: ^0.4.0
  flutter_dotenv: ^5.0.2
  http: ^0.13.5

dev_dependencies:
  flutter_launcher_icons: '^0.13.0'
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/icon.png'

flutter:
  uses-material-design: true

  assets:
    - .env

  fonts:
    - family: SkyFall Done
      fonts:
        - asset: fonts/SkyFall Done.ttf
